### ISSUE TITLE
[Suggestion]Game dont end until Valture has the chance to win

### ISSUE THREAD

**Issue by BukkitGerman** [TheOtherRolesAU/TheOtherRoles#384]
**Is your feature request related to a problem? Please describe.**
When a Valture is alive and there are enoughdead bodys to win the Game. Normaly the Game will end if there are E.g 2 Imposters, 1 Crewmate and 1 Valture. My idea is to dont end the Game until the Valture dont have enough dead bodies / alive player exept the imposter to win.

**Describe the solution / role you'd like**
As long as there are enough corpses + crewmates for the Valture to eat, the game does not end. So the Valture gets the chance to win the game even if the crewmates have already lost it.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by alexasterisk** [comment]
I would not recommend this idea, the main reason why is that the game would end there no matter what. Any odd-case where this would be a possible ending would never work out for the Vulture. For example: one Jackal and one Vulture. According to your change this would be a valid game, but there is no way for the Vulture to win. In your example of two Imposters all they have to do is double kill, your suggestion also assumes that the Vulture has already eaten three bodies making it even more implausible of a situation.

Jackal is one of the roles that bypasses the whole Imposter game-end because it's also a role that has it's own winning condition and the same abilities as the Imposters. Vulture cannot kill and, by most cases, is less of a priority to get out of the game than a killing role.

**Comment by K3ndoo** [comment]
Thanks for this idea, but it didn't make the cut.
