### ISSUE TITLE
Correct Linux installation

### ISSUE THREAD

**Issue by panvid** [TheOtherRolesAU/TheOtherRoles#392]
The link to the configuration of `winhttp.dll` is not working correctly (deeplink is missing).

**Comment by panvid** [comment]
PR is made https://github.com/Eisbison/TheOtherRoles/pull/393

**Comment by homeworkprod** [comment]
> (deeplink is missing)

The link to the relevant page still works, though the in-page anchor does not. Still helpful and better than removing the link altogether, I'd say.

**Comment by homeworkprod** [comment]
BTW, the new deeplink is: https://docs.bepinex.dev/articles/advanced/proton_wine.html

If the `WINEDLLOVERRIDES` approach really does work, I suggest to *add* it to the docs instead of replacing the link with it, because the approach described in the linked docs definitely still works (for me at least).

**Comment by K3ndoo** [comment]
Thanks for the report. If this is still an issue, please let us know in our Discord!
