### ISSUE TITLE
I have hats licence question.

### ISSUE THREAD

**Issue by Dekokiyo** [TheOtherRolesAU/TheOtherRoles#408]
Hello.
I just found a mod that uses TOR's hat even though it's not even a fork of TOR.
Here is that mod.
https://github.com/ykundesu/SuperNewRoles

The creator of this mod explains, "Since the GPL is applied to the hat link, the GPL is also applied to the hat image."
We recently asked him to remove it, but it's still in usable condition.
However, we have actually confirmed that the Hut repository does not have a license, and I'm sure you know that too.
Is this a license violation or different?
If it is a violation, it would be helpful if you could contact the SNR issue directly if possible.

I've attached the link and text of the release notes.
https://github.com/ykundesu/SuperNewRoles/releases/tag/1.4.0.8
![image](https://user-images.githubusercontent.com/97837904/194305056-9c7d7d5f-fc00-4d56-91a2-116362389351.png)
Translate
_New hat "TOR&TORGM"
・Added support for TheOtherRoles and TheOtherRolesGM hats._

Thank you.
Best regards

**Comment by gendelo3** [comment]
This is an interesting question. 

The TheOtherHats repo does indeed not offer a license, especially not GPL.
Thus it is theoretically like this:

`If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.` (This would also apply to any assets, so also to our hats)


On the other hand, personally, I am not sure, if or why we would want to stop anyone using the hats, because they were drawn to be used and we're not a for profit company trying to make money from our mod. It's made so people can have fun, and specifically the mod itself is licensed under the GPL so that anyone can make modifications, as long as they respect the license and give credit.

So thanks for letting us know, we'll discuss the issue internally.

**Comment by Dekokiyo** [comment]
Thanks you too.
