### ISSUE TITLE
[Suggestion] New Neutral Role: Lost Messenger

### ISSUE THREAD

**Issue by CoolLKKPS** [TheOtherRolesAU/TheOtherRoles#434]
I have some ideas for a new Neutral role, I came up with those idea after watching the AU animation made by Rodamrix, so I like to called it "Lost Messenger".

1. The Lost Messenger must at least complete and survive a meeting to able to kill, when this role can able to kill after the meeting ends, this role identity will exposed to all Impostors and they will know who (at least position is still hidden), however this role need to be close to or above the Honor threshold to be killed by the Impostor;
2. Killing Neutral will not have any effect, but killing Crewmate or killing Impostor MAY WILL effect the victory conditions: The Honor threshold;
3. Survive each meeting MAY WILL receive Honor Points;
4. If Honor Points are below or equal the Honor threshold, the victory conditions are consistent with the Impostor; If Honor Points are above the Honor threshold, the victory conditions are consistent with the Crewmate.

**Comment by K3ndoo** [comment]
1. If this role will be revealed to the Impostor, it will be guessed/killed after the first Meeting.
2. So, we need to introduce/implement a system that is yet not implemented. Honor points. How much do you gain after surviving a Meeting? How much do the Impostor need to be killed?
3. Also: It's a new NEUTRAL KILLING ROLE, which is instantly a no due to our "what not to suggest list" in our discord.

Thanks for the suggestion though! :)
